### ISSUE TITLE
Can't run script/server

### ISSUE THREAD

**Issue by cheshire137** [websages/dashboards-bikeshed#37]
I'm getting the following error:

```
% script/server
/Users/cheshire137/.rbenv/versions/2.2.3/lib/ruby/2.2.0/uri/rfc2396_parser.rb:304:in `escape': undefined method `gsub' for nil:NilClass (NoMethodError)
    from /Users/cheshire137/.rbenv/versions/2.2.3/lib/ruby/2.2.0/uri/common.rb:99:in `escape'
    from /Users/cheshire137/code/websages/dashboards-bnagh/jobs/twitter.rb:12:in `<top (required)>'
```

Is this due to not setting any values in .app-env? I just left the file the same as .app-env-dist.

**Comment by stephenyeargin** [comment]
You may need to ensure that the `.app-env` is loaded into memory before starting dashing. There's a helper bash script that may assist with that.

```
$ ./local_test.sh
```

**Comment by stephenyeargin** [comment]
My other dashboards all use `Dotenv` instead, but I haven't quite been ready to refactor this to do the same.

**Comment by stephenyeargin** [comment]
This has been updated a bit. We can re-open if it continues to be troublesome. Addressing #38 will cover bad instructions.
