### ISSUE TITLE
Update buses to match ones we use

### ISSUE THREAD

**Issue by stephenyeargin** [websages/dashboards-bikeshed#48]
- 🌯 🚌 Route 4 - `/route/4/dir/0/stop/MCC4_14`
- 🍺 🚌 Route 28 - `/route/28/dir/1/stop/MCC4_22`
- Route 50 - `/route/50/dir/0/stop/MCC5_1`
- Route 10 - `/route/10/dir/0/stop/MCC5_3`
- Route 19 - `/route/19/dir/1/stop/MCC5_4`
- Route 3 - `/route/3/dir/0/stop/MCC5_5`

**Comment by brandondees** [comment]
for west side rick and I use any one of 19, 10, and 50. I'm not clear on the timings of the new 19 route yet but it does have a stop on our actual block so if it's frequent enough I think we're most likely to default to it now.

**Comment by northrup** [comment]
I’m always on the #7

**Comment by rick** [comment]
What @brandondees said.  Also, if space is not an issue, the #3 goes to white bridge + charlotte and I've taken it in a pinch from time to time. But if space is an issue, #50, #10, #19 are the main west side buses.

**Comment by rick** [comment]
Heh, pretty sure I just linked to a bunch of issues and PRs.
